#!/bin/sh
echo "Test de $1 : "
./$1 $1.output 2>/dev/null 1>&2
if [ ! -f $1.result ]
then
  echo fichier $1.result absent, je ne peux verifier les resultats
  exit 1
fi
if [ -n "`diff $1.output $1.result`" ]
then
  echo "ECHEC"
  echo "Le test a echoue verifiez votre programme ou utilisez le debugger"
  exit 1
else
  echo "SUCCES"
  echo "Le test est un succes, vous pouvez passer a l'exercice suivant"
  exit 0
fi
